Use correct name of generated file.
In commit 97a432a58ed2b1db9e5b66ab89fce927e89b4276 the name of the
generated file was fixed in `ngin`, but the same problem is also
present in `ngin2d`.

This fixes the following compilation error:

  Building CXX object dom/lgm/ngin2d/CMakeFiles/ngin2.dir/ngin-lex.cc.o
  ngin-lex.ll:26:24: fatal error: ngin-yacc.hh: No such file or directory